---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.5.1
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: false
    checksum: false
    download: false
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: true
    system: false
    tags: true
    version: false
app_desc: an agentless automation tool that you install on a single host (referred
    to as the control node).
app_name: ansible
app_repo: https://github.com/ansible/ansible
app_type: python
app_website: https://docs.ansible.com/
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master|a|b)
custom_require_commands: python
install_map_enabled: true
install_map_method: link
install_map_yaml:
    venv/bin/ansible: bin/ansible
    venv/bin/ansible-config: bin/ansible-config
    venv/bin/ansible-connection: bin/ansible-connection
    venv/bin/ansible-console: bin/ansible-console
    venv/bin/ansible-doc: bin/ansible-doc
    venv/bin/ansible-galaxy: bin/ansible-galaxy
    venv/bin/ansible-inventory: bin/ansible-inventory
    venv/bin/ansible-playbook: bin/ansible-playbook
    venv/bin/ansible-pull: bin/ansible-pull
    venv/bin/ansible-test: bin/ansible-test
    venv/bin/ansible-vault: bin/ansible-vault
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-ansible-core
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-ansible-core.git
python_name: ansible-core
source_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
